# Generated by Django 3.2.5 on 2021-07-24 13:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='Время подачи заявки')),
                ('type', models.CharField(blank=True, choices=[('ремонт', 'ремонт'), ('обслуживание', 'обслуживание'), ('консультация', 'консультация')], max_length=300, null=True, verbose_name='Тип заявки')),
                ('status', models.CharField(blank=True, choices=[('в работе', 'в работе'), ('закрыта', 'закрыта')], max_length=300, null=True, verbose_name='Статус заявки')),
                ('workers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixing.worker')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('workers', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fixing.worker')),
            ],
            options={
                'verbose_name': 'Консультация',
                'verbose_name_plural': 'Консультации',
            },
        ),
    ]
